### ISSUE TITLE
.html extension instead of .md

### ISSUE THREAD

**Issue by CaryLandholt** [sindresorhus/gulp-markdown#1]
Any way to apply .html as the file extension?

``` JavaScript
gulp.src('./src/**/*.md')
.pipe(markdown())
.pipe(gulp.dest('./dest/'))
```

The above results in successfully compiled html files but with the .md extension.

Thanks

**Comment by mlynch** [comment]
Seems like this must have broken again in 2.0.1? My gulp process is outputting `.md` files, and it seems to be a version issue as my other machine running an older version of `gulp-markdown` properly renames to `.html`.

**Comment by imshuffling** [comment]
This still appears to be broken, anyone found a solution?
