### ISSUE TITLE
marked working with custom renderer, but trying to use custom renderer via markdown fails.

### ISSUE THREAD

**Issue by mikemaccana** [sindresorhus/gulp-markdown#11]
Sorry about this, I have some perfectly working code using marked and I just can't seem to get it to work via gulp-markdown.

Here's the working code:

	var log = console.log.bind(console)

	var marked = require('marked');
	var renderer = new marked.Renderer();
	var realTableCellRenderer = renderer.tablecell
	renderer.tablecell = function(content, flags){
		flags.align = null;
		return realTableCellRenderer(content, flags)
	}

	var markdown = `
	| API        | Documented CSP Policy           |
	| ------------- |:-------------:|
	|Google Fonts|No documented policy|
	|Mixpanel|No documented policy|
	|Ractive.js|[Documented policy](http://docs.ractivejs.org/edge/csp)|
	|Stripe|[Documented policy](https://support.stripe.com/questions/what-about-pci-dss-3-1)|
	|Twitter oembed API|No documented policy, but [some CSP notes](https://dev.twitter.com/web/overview/widgets-webpage-properties#csp)|
	|Typekit|[Documented policy](http://help.typekit.com/customer/portal/articles/1265956-content-security-policy-and-typekit)|
	|Stormpath|No documented policy|

	`

	log(marked(markdown, { renderer: renderer }));

You'll note the output here doesn't contain any `style` attributes on the `td` elements. Yaay.

Reading the gulp-markdown and marked docs this seems to be the correct syntax:

	// Stop marked spewing CSS into out HTML
	var customMarkdownRenderer = new markdown.marked.Renderer();
	var realTableCellRenderer = customMarkdownRenderer.tablecell;
	customMarkdownRenderer.tablecell = function(content, flags){
		flags.align = null; 
		return realTableCellRenderer(content, flags)
	}

And then:

	.pipe(markdown({
		renderer: customMarkdownRenderer
	}))

How can I use a custom renderer in gulp-markdown?

**Comment by sindresorhus** [comment]
I dunno. I'm passing passing [0] the options to marked according to its docs [1]:

\[0]: https://github.com/sindresorhus/gulp-markdown/blob/a4b1d4532ab54c008b1b3cafc35cd1e937941d6b/index.js#L18
\[1]: https://github.com/chjj/marked#options
