### ISSUE TITLE
strong text is incorrectly converted

### ISSUE THREAD

**Issue by 10101010101** [sindresorhus/gulp-markdown#15]
MARKDOWN:

`A local server stack, such as LAMP (**L**inux **A**pache **M**ySQL/**M**ariaDB **P**HP) or WAMP (**W**indows **A**pache **M**ySQL/**M**ariaDB **P**HP)`

HTML:

`A local server stack, such as LAMP (<strong>L*<em>inux *</em>A</strong>pache <strong>M**ySQL/</strong>M<strong>ariaDB **P</strong>HP) or WAMP (<strong>W*<em>indows *</em>A</strong>pache <strong>M**ySQL/</strong>M<strong>ariaDB **P</strong>HP)`

in various online converters, etc. it's ok

**Comment by sindresorhus** [comment]
From the top of the readme:

> Issues with the output should be reported on the marked issue tracker.
