### ISSUE TITLE
Vulnerability in marked package

### ISSUE THREAD

**Issue by philmayfield** [sindresorhus/gulp-markdown#21]
Mitre has identified two new high severity CVEs in the `marked` package for versions `< 4.0.10`.

[https://github.com/advisories/GHSA-rrrm-qjm4-v8hf](https://github.com/advisories/GHSA-rrrm-qjm4-v8hf)
[https://github.com/advisories/GHSA-5v2h-r2cx-5xgj](https://github.com/advisories/GHSA-5v2h-r2cx-5xgj)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-markdown/releases/tag/v7.0.0

**Comment by philmayfield** [comment]
Thank you! 🙇
