### ISSUE TITLE
Enquiry about precompile and postcompile function options

### ISSUE THREAD

**Issue by simevidas** [sindresorhus/gulp-markdown#5]
grunt-markdown has [`preCompile` and `postCompile` options](https://github.com/treasonx/grunt-markdown#modifying-content-with-precompile-and-postcompile) for performing custom modifications to the file contents before/after the Markdown-to-HTML conversion. 

Do you think it would make sense to integrate this feature into your plugin?

**Comment by sindresorhus** [comment]
Nope, you can easily do that with something like https://github.com/geejs/gulp-tap
