### ISSUE TITLE
specify a layout template

### ISSUE THREAD

**Issue by chovy** [sindresorhus/gulp-markdown#6]
Is it possible to specify a layout template, that includes `<html>` etc.

**Comment by sindresorhus** [comment]
You can use https://github.com/KenPowers/gulp-cheerio to manipulete the HTML however you want after the Markdown conversion. I'm trying to keep this plugin simple and focused.

**Comment by seriema** [comment]
[gulp-wrapper](https://www.npmjs.com/package/gulp-wrapper) worked great for me as `gulp-cheerio` seemed to be more about manipulating the output.
