### ISSUE TITLE
GFM and syntax highlighting?

### ISSUE THREAD

**Issue by dpipkin** [sindresorhus/gulp-markdown#7]
I haven't been able to get gfm tables and syntax highlighting to work...

Here's my gulpfile:
```
var gulp = require('gulp');
var markdown = require('gulp-markdown');
var livereload = require('gulp-livereload');

gulp.task('markdown', function() {
  return gulp.src('*.md')
      .pipe(markdown({
        highlight: function(code) {
          return require('highlight.js').highlightAuto(code).value;
        }
      }))
      .pipe(gulp.dest('./'))
      .pipe(livereload());
});

gulp.task('watch', function() {
  livereload.listen();
  gulp.watch('*.md', ['markdown']);
});
```

**Comment by dpipkin** [comment]
Never mind about the tables.. Turns out I just don't have nice styling in place so I didn't notice it.

**Comment by hoodsy** [comment]
@dpipkin what'd your markdown look like? I'm using essentially the same markdown task with the GFM syntax to specify an html code block, with no success.

**Comment by dpipkin** [comment]
I can't remember haha. I never did get the syntax highlighting to work though.
