### ISSUE TITLE
callback passing to marked seems unsupported

### ISSUE THREAD

**Issue by anaran** [sindresorhus/gulp-markdown#8]
Perhaps I don't grok it, but it seems that cb should be passed in after options at [module.exports = function \(options\)](https://github.com/sindresorhus/gulp-markdown/search?utf8=%E2%9C%93&q=%22module.exports+%3D+function+\%28options\%29%22&type=Code)

gulp-marked had the problem it never actually called the `cb` and [my pull request](https://github.com/lmtm/gulp-marked/commit/dddf0e8dc55055c0aebb52e15d0019517fc2ab23) fixed it there.

Would be great to learn how I can pass the callback already, for what I try to do [here](https://github.com/anaran/IssuePigeonFirefox/search?utf8=%E2%9C%93&q=%22addTableOfContents%22&type=Code) or if this feature could be implemented if indeed missing.

Thanks!

**Comment by sindresorhus** [comment]
It doesn't need a callback as it returns a [stream](http://maxogden.com/node-streams.html).

For what you're trying to do you can just use https://github.com/geejs/gulp-tap and modify the `file.contents`. This is out of the scope of this plugin.

**Comment by anaran** [comment]
Thanks for the quick reply.

Adding yet another node package for working around a lacking feature of a marked wrapper seems wrong to me.

I'll just stay with [gulp-marked](https://github.com/lmtm/gulp-marked) instead.

**Comment by sindresorhus** [comment]
Ok, good luck. You're missing the point of gulp, though; Small focused plugins doing one thing.

Why even use multiple plugins? You could just have one master plugin called `anaran` that does everything from making you breakfast to compiling markdown from sheep wool.
