### ISSUE TITLE
Expose marked object

### ISSUE THREAD

**Issue by mariusGundersen** [sindresorhus/gulp-markdown#9]
It would be neat if this plugin could expose the marked object it is using, so it can be modified. `marked` exposes (for example) the `Renderer` class which is useful to modify with custom rendering. This is not possible using only this plugin now, but requires only a single line of code to make possible.

**Comment by sindresorhus** [comment]
:+1: 

Btw, no need to open both a PR and issue. PRs are issues ;)

**Comment by mariusGundersen** [comment]
Sorry for opening both, realised afterwards that I could do it myself :laughing:
